; Assembly Level Program 14a
; Read a pair of input co-ordinates in BCD and move the cursor to the specified location on the screen.

.MODEL SMALL
.STACK
.DATA
XMSG DB 13,10,'ENTER VALUE OF X CO-ORDINATES:','$'
X DB ?
YMSG DB 13,10,'ENTER VALUE OF Y CO-ORDINATES:','$'
Y DB ?
.CODE
MOV AX,@DATA
MOV DS,AX
MOV DX,OFFSET XMSG ;TO READ BCD CO=ORDINATES
CALL READ_BCD
MOV X,BH
MOV DX,OFFSET YMSG
CALL READ_BCD
MOV Y,BH
MOV AH,0 ;TO CLEAR THE SCREEN
MOV AL,03
INT 10H
MOV AH,02H ;TO SET CURSOR POSITION
MOV DH,X
MOV DL,Y
MOV BH,0
INT 10H
MOV DL,'-'
MOV AH,06H
INT 21H
MOV AH,4CH
INT 21H
READ_BCD PROC
MOV AH,09H
INT 21H
MOV AH,01H ;FIRST DIGIT
INT 21H
MOV BH,AL
MOV AH,01H ;SECOND DIGIT
INT 21H
MOV BL,AL
MOV CL,4H
SUB BH,30H ;TO CONVERT FROM ASCII TO BCD
SUB BL,30H
SHL BH,CL
OR BH,BL
RET
READ_BCD ENDP
END